#!/usr/bin/env bash
# Regenerates deploy/erpnext/docker-compose.yaml from frappe_docker's
# compose.yaml plus the mariadb, redis and noproxy overrides and our
# compose.local.yaml (CC-102). The output is committed.
#
# Usage: deploy/erpnext/generate-compose.sh
#
# The output must hold only frappe_docker's development defaults (database
# root password 123), never a real secret. So `docker compose config` runs in
# a scrubbed environment: a DB_PASSWORD or other variable exported in your
# shell, or set in .env, cannot leak into the committed file.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
fd="$root/deploy/frappe_docker"
out="$root/deploy/erpnext/docker-compose.yaml"

if [[ ! -f "$fd/compose.yaml" ]]; then
	echo "generate-compose: $fd is empty; run: git submodule update --init deploy/frappe_docker" >&2
	exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Only what the docker CLI needs to find its engine, plus our settings.
# ERPNEXT_VERSION is set empty to silence compose's "not set" warning; it is
# only the fallback for CUSTOM_TAG.
env -i \
	PATH="$PATH" \
	HOME="$HOME" \
	${DOCKER_HOST:+DOCKER_HOST="$DOCKER_HOST"} \
	${DOCKER_CONTEXT:+DOCKER_CONTEXT="$DOCKER_CONTEXT"} \
	${DOCKER_CONFIG:+DOCKER_CONFIG="$DOCKER_CONFIG"} \
	CUSTOM_IMAGE=close-copilot/erpnext \
	CUSTOM_TAG=15 \
	PULL_POLICY=never \
	FRAPPE_SITE_NAME_HEADER=erp.localhost \
	ERPNEXT_VERSION= \
	docker compose \
	--project-name close-copilot-erpnext \
	--project-directory "$fd" \
	-f "$fd/compose.yaml" \
	-f "$fd/overrides/compose.mariadb.yaml" \
	-f "$fd/overrides/compose.redis.yaml" \
	-f "$fd/overrides/compose.noproxy.yaml" \
	-f "$root/deploy/erpnext/compose.local.yaml" \
	config >"$tmp"

{
	echo "# GENERATED by deploy/erpnext/generate-compose.sh from deploy/frappe_docker"
	echo "# (pinned submodule) and deploy/erpnext/compose.local.yaml. Do not edit by hand."
	echo "# Development defaults only: MariaDB root password 123, no real secrets."
	cat "$tmp"
} >"$out"

echo "generate-compose: wrote ${out#"$root"/}"
